# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XepOCQS5iMvo0L3OeZIhZVj7XRvxu6d4
"""

string = input("Enter the string: ")
output = {x : string.count(x) for x in set(string)} 
print (str(output))
